### ISSUE TITLE
a way to input multiple scores other than CADD?

### ISSUE THREAD

**Issue by samskim** [jeremymcrae/fitDNM#1]
(This is more of a question than an issue)

Is there a way to incorporate multiple functional scores (let's say CADD and PolyPhen) other than a single score? 
On the separate note, what format would these scores should be if multi columned?

**Comment by jeremymcrae** [comment]
I think it would have to be reduced it to a single score at some point for fitDNM analysis, since the fitDNM model sums across pathogenicity scores and mutation rates.

You could certainly swap in different functional scores though, so long as they follow the CADD table format. CADD table columns are: chromosome, position, ref allele, alt allele, raw score, scaled score. This package only uses the scaled score column, drops the 'raw' value after loading. Table needs to be bgzipped, tab-separated, and tabix indexed. There might be other restrictions too e.g. might not permit 'nan' missing data values in the table?

Hope that helps!
